import type { StatsDisplayUnit } from "./display";

export type MetricUnit = StatsDisplayUnit;
export type SampleKind = "scoreboard" | "kills" | "rounds" | "openings" | "openingWins" | "openingLosses" | "deaths" | "flashes" | "throws" | "attempts" | "pistolRounds" | "opportunities" | "plants" | "weaponKills" | "maps";
export type MetricSampleMode = "fraction" | "denominator" | "hidden";

const sampleLabels: Record<SampleKind, string> = {
  scoreboard: "maps",
  kills: "kills",
  rounds: "rounds",
  openings: "openings",
  openingWins: "opening wins",
  openingLosses: "opening losses",
  deaths: "deaths",
  flashes: "flashes",
  throws: "throws",
  attempts: "attempts",
  pistolRounds: "pistol rounds",
  opportunities: "opportunities",
  plants: "plants",
  weaponKills: "weapon kills",
  maps: "maps",
};

function metric<K extends SampleKind>(
  label: string,
  unit: MetricUnit,
  precision: number,
  sampleKind: K,
  description: string,
  options: { sampleMode?: MetricSampleMode; rankingSampleKind?: SampleKind | null } = {},
) {
  return {
    label,
    unit,
    precision,
    sampleKind,
    sampleLabel: sampleLabels[sampleKind],
    description,
    sampleMode: options.sampleMode ?? "fraction",
    rankingSampleKind: options.rankingSampleKind ?? null,
    rankingSampleLabel: options.rankingSampleKind ? sampleLabels[options.rankingSampleKind] : null,
  } as const;
}

export const STATS_METRICS = {
  rating: metric("Rating", "number", 2, "scoreboard", "综合衡量选手或队伍整体表现的评分，适合横向比较当前统计范围内的发挥。", { rankingSampleKind: "rounds" }),
  adr: metric("ADR", "number", 1, "scoreboard", "平均每回合造成的伤害。", { rankingSampleKind: "rounds" }),
  kd: metric("K/D", "number", 2, "scoreboard", "击杀数与死亡数的比值。", { rankingSampleKind: "rounds" }),
  kpr: metric("KPR", "perRound", 2, "scoreboard", "平均每回合击杀数。", { rankingSampleKind: "rounds" }),
  hs: metric("HS%", "ratioPercent", 1, "kills", "爆头击杀占全部击杀的比例。", { rankingSampleKind: "kills" }),
  we: metric("WE", "number", 1, "scoreboard", "武器效率，用于描述选手的击杀产出。", { rankingSampleKind: "rounds" }),
  rws: metric("RWS", "number", 2, "scoreboard", "回合胜利贡献指标（Round Win Shares）。", { rankingSampleKind: "rounds" }),
  mk: metric("MK/100r", "per100Round", 1, "scoreboard", "每 100 回合多杀回合数。", { rankingSampleKind: "rounds" }),
  multiKillRoundRate: metric("2K+ Round%", "ratioPercent", 1, "rounds", "取得至少双杀的回合占全部出场回合的比例。", { rankingSampleKind: "rounds" }),
  openingAttempt: metric("Attempts%", "ratioPercent", 1, "rounds", "参与首杀对枪的回合占全部出场回合的比例；首杀对枪包括本人取得首杀或成为首个阵亡者。", { rankingSampleKind: "rounds" }),
  openingAttempts: metric("Attempts", "count", 0, "openings", "当前统计范围内参与首杀对枪的总次数，即首杀次数与首死次数之和。", { sampleMode: "hidden" }),
  openingWin: metric("Success%", "ratioPercent", 1, "openings", "首杀对枪胜率：本人取得首杀的次数 ÷ 本人参与首杀对枪的次数。", { rankingSampleKind: "openings" }),
  openingWins: metric("Opening wins", "count", 0, "openingWins", "当前统计范围内本人赢下首杀对枪、取得首杀的总次数。", { sampleMode: "hidden" }),
  winAfterOpeningWin: metric("Win after FK", "ratioPercent", 1, "openingWins", "本人取得首杀的回合中，所在队伍最终赢下该回合的比例。分母是本人取得首杀的回合数。", { rankingSampleKind: "openingWins" }),
  winAfterOpeningLoss: metric("Win after FD", "ratioPercent", 1, "openingLosses", "本人在首杀对枪中失利、成为首个阵亡者的回合中，所在队伍最终翻盘赢下该回合的比例。分母是本人首死的回合数。", { rankingSampleKind: "openingLosses" }),
  firstKill: metric("FK/100r", "per100Round", 2, "rounds", "每 100 回合取得首杀的次数。", { rankingSampleKind: "rounds" }),
  firstDeath: metric("FD/100r", "per100Round", 2, "rounds", "每 100 回合成为首个阵亡者的次数。", { rankingSampleKind: "rounds" }),
  kast: metric("KAST", "ratioPercent", 1, "rounds", "完成击杀、助攻、存活或被队友及时补枪的回合占比。", { rankingSampleKind: "rounds" }),
  survival: metric("Survival%", "ratioPercent", 1, "rounds", "回合结束时存活的回合占比。", { rankingSampleKind: "rounds" }),
  trade: metric("Trade/100r", "per100Round", 1, "rounds", "每 100 回合完成的补枪击杀次数。", { rankingSampleKind: "rounds" }),
  tradeKillShare: metric("Trade Kill Share", "ratioPercent", 1, "kills", "补枪击杀占本人全部击杀的比例。", { rankingSampleKind: "kills" }),
  tradedDeathRate: metric("Traded Deaths/100r", "per100Round", 1, "rounds", "每 100 回合本人阵亡后被队友及时补枪的次数，用于描述可交易的前置风险。", { rankingSampleKind: "rounds" }),
  traded: metric("Traded%", "ratioPercent", 1, "deaths", "本人阵亡后被队友及时补枪的死亡占比。", { rankingSampleKind: "deaths" }),
  openingDeathTradedRate: metric("Opening Deaths Traded%", "ratioPercent", 1, "openingLosses", "本人首死后被队友及时补枪的比例。", { rankingSampleKind: "openingLosses" }),
  assist: metric("A/100r", "per100Round", 1, "rounds", "每 100 回合取得的助攻次数。", { rankingSampleKind: "rounds" }),
  tradedOpening: metric("Opening deaths traded", "count", 0, "openings", "本人输掉首杀对枪后，该次死亡被队友及时补枪的次数。", { sampleMode: "hidden" }),
  grenadeUsage: metric("Nades/r", "perRound", 2, "rounds", "平均每回合投掷的闪光、HE、燃烧弹和烟雾弹总数。", { rankingSampleKind: "rounds" }),
  utility: metric("Util/r", "perRound", 2, "rounds", "平均每回合道具伤害。", { rankingSampleKind: "rounds" }),
  flashAssist: metric("FA/100r", "per100Round", 2, "rounds", "每 100 回合闪光助攻次数。", { rankingSampleKind: "rounds" }),
  flashesThrown: metric("Flashes thrown", "count", 0, "throws", "当前统计范围内投掷闪光弹的总次数。", { sampleMode: "hidden" }),
  blindPerFlash: metric("Blind/Flash", "seconds", 2, "flashes", "每颗闪光对敌方造成的平均致盲时间。", { sampleMode: "denominator", rankingSampleKind: "flashes" }),
  netBlindPerFlash: metric("Net Blind/Flash", "seconds", 2, "flashes", "每颗闪光对敌方产生的平均净致盲时间。", { sampleMode: "denominator", rankingSampleKind: "flashes" }),
  enemyBlindPerRound: metric("Enemy blind/r", "seconds", 2, "rounds", "平均每回合对敌方造成的致盲时间。", { rankingSampleKind: "rounds" }),
  teamBlindPerRound: metric("Team blind/r", "seconds", 2, "rounds", "平均每回合对队友造成的致盲时间。", { rankingSampleKind: "rounds" }),
  heThrows: metric("HE thrown", "count", 0, "throws", "当前统计范围内投掷 HE 手雷的总次数。", { sampleMode: "hidden" }),
  hePerRound: metric("HE/r", "perRound", 2, "rounds", "平均每回合由 HE 手雷造成的伤害。", { rankingSampleKind: "rounds" }),
  hePerThrow: metric("HE dmg/throw", "number", 1, "throws", "每次投掷 HE 手雷平均造成的伤害。", { sampleMode: "denominator", rankingSampleKind: "throws" }),
  fireThrows: metric("Fire thrown", "count", 0, "throws", "当前统计范围内投掷燃烧弹或燃烧瓶的总次数。", { sampleMode: "hidden" }),
  firePerRound: metric("Fire/r", "perRound", 2, "rounds", "平均每回合由燃烧弹或燃烧瓶造成的伤害。", { rankingSampleKind: "rounds" }),
  firePerThrow: metric("Fire dmg/throw", "number", 1, "throws", "每次投掷燃烧弹或燃烧瓶平均造成的伤害。", { sampleMode: "denominator", rankingSampleKind: "throws" }),
  smokesThrown: metric("Smokes thrown", "count", 0, "throws", "当前统计范围内投掷烟雾弹的总次数。", { sampleMode: "hidden" }),
  smokePerRound: metric("Smoke/r", "perRound", 2, "rounds", "平均每回合投掷的烟雾弹数量。", { rankingSampleKind: "rounds" }),
  utilityKills: metric("Utility K/100r", "per100Round", 2, "rounds", "每 100 回合由伤害型道具造成的击杀。", { rankingSampleKind: "rounds" }),
  clutchAttempts: metric("Attempts", "count", 0, "attempts", "当前统计范围内进入 1vX 残局的总次数。", { sampleMode: "hidden" }),
  clutchWins: metric("Wins", "count", 0, "attempts", "当前统计范围内赢下 1vX 残局的总次数。", { sampleMode: "hidden" }),
  clutch: metric("Clutch%", "ratioPercent", 1, "attempts", "残局胜率：赢下的 1vX 残局次数 ÷ 残局尝试次数。", { rankingSampleKind: "attempts" }),
  clutchSplit: metric("1vX%", "ratioPercent", 1, "attempts", "对应人数残局的胜率，例如 1v2 表示独自面对两名对手时的残局胜率；分母为该 1vX 场景的尝试次数。", { rankingSampleKind: "attempts" }),
  clutchFrequency: metric("C/100r", "per100Round", 2, "rounds", "每 100 回合赢下的 1vX 残局次数：残局胜利次数 ÷ 出场回合数 × 100。", { rankingSampleKind: "rounds" }),
  clutchAttemptRate: metric("Clutch Attempts/100r", "per100Round", 2, "rounds", "每 100 回合进入 1vX 残局的次数。", { rankingSampleKind: "rounds" }),
  pistol: metric("Pistol Win%", "ratioPercent", 1, "pistolRounds", "手枪局胜率。", { rankingSampleKind: "pistolRounds" }),
  roundWin: metric("RW%", "ratioPercent", 1, "rounds", "回合胜率。", { rankingSampleKind: "rounds" }),
  conversion: metric("R2 Conv", "ratioPercent", 1, "opportunities", "手枪局取胜后继续赢下第二回合的比例。", { rankingSampleKind: "opportunities" }),
  break: metric("R2 Break", "ratioPercent", 1, "opportunities", "手枪局失利后赢下第二回合的比例。", { rankingSampleKind: "opportunities" }),
  fiveVFour: metric("5v4", "ratioPercent", 1, "opportunities", "进入 5v4 人数优势后赢下该回合的比例。", { rankingSampleKind: "opportunities" }),
  fourVFive: metric("4v5", "ratioPercent", 1, "opportunities", "进入 4v5 人数劣势后赢下该回合的比例。", { rankingSampleKind: "opportunities" }),
  fiveVThree: metric("5v3", "ratioPercent", 1, "opportunities", "进入 5v3 人数优势后赢下该回合的比例。", { rankingSampleKind: "opportunities" }),
  threeVFive: metric("3v5", "ratioPercent", 1, "opportunities", "进入 3v5 人数劣势后赢下该回合的比例。", { rankingSampleKind: "opportunities" }),
  ecoSemi: metric("Eco/Semi Win%", "ratioPercent", 1, "opportunities", "低经济方对高经济方的回合胜率。", { rankingSampleKind: "opportunities" }),
  plantConversion: metric("Plant conv", "ratioPercent", 1, "plants", "完成下包后的回合胜率。", { rankingSampleKind: "plants" }),
  headshot: metric("HS%", "ratioPercent", 1, "kills", "爆头击杀占全部击杀的比例。", { rankingSampleKind: "kills" }),
  killShare: metric("Kill share", "ratioPercent", 1, "weaponKills", "该武器击杀占当前范围全部武器击杀的比例。", { rankingSampleKind: "weaponKills" }),
  sniperKillShare: metric("Sniper Kill Share", "ratioPercent", 1, "weaponKills", "AWP 与 SSG 08 击杀占本人全部武器击杀的比例，用于描述狙击角色使用强度。", { rankingSampleKind: "weaponKills" }),
  killsPerRound: metric("Kills/r", "perRound", 2, "rounds", "平均每回合击杀数。", { rankingSampleKind: "rounds" }),
  damagePerRound: metric("ADR", "perRound", 1, "rounds", "平均每回合伤害。", { rankingSampleKind: "rounds" }),
  rounds: metric("Rounds", "count", 0, "rounds", "出场回合数。", { sampleMode: "hidden" }),
  maps: metric("Maps", "count", 0, "maps", "出场地图数。", { sampleMode: "hidden" }),
} as const;

export type StatsMetricKey = keyof typeof STATS_METRICS;
