import { describe,it,expect } from "vitest";
import { marketIsLocked,resolveBetFact,type MarketFactInput } from "./domain";
import { roundLineTwice } from "./policy";
const base:MarketFactInput={type:"match_winner",subject:{kind:"match",entryIds:["a","b"],runId:"q",format:"bo3",mapPool:[]},line:null,voidedAt:null,match:{id:"m",entryAId:"a",entryBId:"b",majorStageRunId:null,qualificationRunId:"q",format:"bo3",status:"in_progress",isForfeit:false,startedAt:null,scoreA:null,scoreB:null},maps:[],veto:{startedAt:new Date(),completedAt:null,mapPoolSnapshot:["de_a","de_b","de_c"],pendingAppeal:false},event:{entryIds:[],playerIds:[],started:false,champion:null,kills:null}};
describe("BET canonical lifecycle",()=>{
  it("BP does not lock series markets, actual gameplay does",()=>{expect(marketIsLocked(base)).toBe(false);expect(marketIsLocked({...base,type:"veto_first"})).toBe(true);expect(marketIsLocked({...base,match:{...base.match!,startedAt:new Date()}})).toBe(true);});
  it("locks each map independently after previous map completion",()=>{const m={id:"map2",matchId:"m",mapOrder:2,mapName:"de_a",startedAt:null,completedAt:null,scoreA:null,scoreB:null};const input:MarketFactInput={...base,type:"map_winner",subject:{kind:"map",entryIds:["a","b"],runId:"q",format:"bo3",mapId:m.id,mapOrder:2,mapName:m.mapName},match:{...base.match!,startedAt:new Date()},maps:[m]};expect(marketIsLocked(input)).toBe(false);expect(marketIsLocked({...input,maps:[{...m,startedAt:new Date()}]})).toBe(true);});
  it("BP waits for appeals and decider settles without being played",()=>{const input={...base,type:"veto_decider" as const,veto:{...base.veto!,completedAt:new Date(),pendingAppeal:true},maps:[{id:"last",matchId:"m",mapOrder:3,mapName:"de_c",startedAt:null,completedAt:null,scoreA:null,scoreB:null}]};expect(resolveBetFact(input).state).toBe("pending");expect(resolveBetFact({...input,veto:{...input.veto,pendingAppeal:false}})).toMatchObject({state:"confirmed",winningKeys:["de_c"]});});
  it("refunds forfeit, missing match, and frozen subject mismatch",()=>{for(const input of [{...base,match:undefined},{...base,match:{...base.match!,isForfeit:true}},{...base,match:{...base.match!,entryBId:"c"}}])expect(resolveBetFact(input).state).toBe("void");});
  it("settles O/U including overtime, returns to pending on unconfirmed result",()=>{const map={id:"map",matchId:"m",mapOrder:1,mapName:"de_a",startedAt:new Date(),completedAt:new Date(),scoreA:16,scoreB:14};const input:MarketFactInput={...base,type:"total_rounds",line:43,subject:{kind:"map",entryIds:["a","b"],runId:"q",format:"bo3",mapId:map.id,mapOrder:1,mapName:map.mapName},maps:[map]};expect(resolveBetFact(input)).toMatchObject({state:"confirmed",winningKeys:["over"]});expect(resolveBetFact({...input,maps:[{...map,completedAt:null}]}).state).toBe("pending");});
  it("top fraggers require complete statistics and split ties",()=>{const input:MarketFactInput={...base,type:"top_fragger",subject:{kind:"event",entryIds:["a","b"],playerIds:["p","q"]},event:{entryIds:["a","b"],playerIds:["p","q"],started:true,champion:"a",kills:null}};expect(resolveBetFact(input).state).toBe("pending");expect(resolveBetFact({...input,event:{...input.event,kills:[{userId:"p",kills:90},{userId:"q",kills:90}]}})).toMatchObject({state:"confirmed",winningKeys:["p","q"]});});
  it("creates deterministic half lines with a sample fallback",()=>{expect(roundLineTwice([],[])).toBe(43);expect(roundLineTwice([22,20,25],[13,13,13])).toBe(43);expect(roundLineTwice([25],[24,22,20])).toBe(43);});
});
