const WEAPON_LABELS: Record<string, string> = {
  "AK-47": "AK47",
  "M4A4": "M4A4",
  "M4A1-S": "M4A1",
  "AWP": "AWP",
  "SSG 08": "SSG 08",
  "Desert Eagle": "Deagle",
  "Glock-18": "Glock",
  "USP-S": "USP",
  "P2000": "P2000",
  "P250": "P250",
  "Five-SeveN": "FN57",
  "Tec-9": "Tec-9",
  "CZ75-Auto": "CZ75",
  "Dual Berettas": "双枪",
  "MAC-10": "MAC-10",
  "MP9": "MP9",
  "MP7": "MP7",
  "MP5-SD": "MP5",
  "UMP-45": "UMP45",
  "P90": "P90",
  "PP-Bizon": "野牛",
  "FAMAS": "FAMAS",
  "Galil AR": "Galil",
  "SG 553": "SG553",
  "AUG": "AUG",
  "MAG-7": "MAG-7",
  "Nova": "Nova",
  "XM1014": "XM1014",
  "M249": "M249",
  "Negev": "Negev",
  "Zeus x27": "Zeus",
  "Molotov": "Molotov",
  "Flashbang": "Flash",
  "HE Grenade": "HE",
  "Smoke Grenade": "Smoke",
};

export function displayWeaponName(raw: string): string {
  return WEAPON_LABELS[raw] ?? raw;
}
