import { and, asc, eq, inArray, isNotNull, or } from "drizzle-orm";
import { alias } from "drizzle-orm/pg-core";
import { notFound } from "next/navigation";
import { db } from "@/db/client";
import { communityAwards, competitionEntries, matches, seasons, users } from "@/db/schema";
import { CommunityAwardsBoard } from "@/components/community-awards/CommunityAwardsBoard";
import { getCurrentUserAuthorization } from "@/lib/auth/session";
import { getSeasonAwardCandidates, isPublicCommunityAward, PUBLIC_COMMUNITY_AWARD_STATUSES } from "@/lib/community-awards/read-model";
import { getPublicDisplayName } from "@/lib/identity/display-name";
import { presentMatchLabel } from "@/lib/matches/presentation";
import { normalizeStagePlan } from "@/types/season";

async function getPublicAwardData(seasonId: string, currentUserId: string | null, stagePlan: ReturnType<typeof normalizeStagePlan>) {
  const recipient = alias(users, "community_award_recipient");
  const publicAward = or(inArray(communityAwards.status, PUBLIC_COMMUNITY_AWARD_STATUSES), and(eq(communityAwards.status, "withdrawn"), isNotNull(communityAwards.reviewedAt)));
  const rows = await db.select({ id: communityAwards.id, submittedByUserId: communityAwards.submittedByUserId, name: communityAwards.name, condition: communityAwards.condition, prize: communityAwards.prize, supplementaryNote: communityAwards.supplementaryNote, publicNote: communityAwards.publicNote, reviewNote: communityAwards.reviewNote, reviewedAt: communityAwards.reviewedAt, status: communityAwards.status, outcomeNote: communityAwards.outcomeNote, submitter: { displayName: users.displayName, perfectName: users.perfectName, steamName: users.steamName }, recipient: { displayName: recipient.displayName, perfectName: recipient.perfectName, steamName: recipient.steamName } }).from(communityAwards).innerJoin(users, eq(communityAwards.submittedByUserId, users.id)).leftJoin(recipient, eq(communityAwards.recipientUserId, recipient.id)).where(and(eq(communityAwards.seasonId, seasonId), currentUserId ? or(publicAward, eq(communityAwards.submittedByUserId, currentUserId)) : publicAward)).orderBy(asc(communityAwards.createdAt));
  const [candidates, matchRows] = await Promise.all([getSeasonAwardCandidates(seasonId), db.select({ id: matches.id, stage: matches.stage, round: matches.round, entryRound: matches.entryRound, aName: competitionEntries.name, bId: matches.entryBId }).from(matches).innerJoin(competitionEntries, eq(matches.entryAId, competitionEntries.id)).where(eq(matches.seasonId, seasonId))]);
  const bIds = [...new Set(matchRows.map((row) => row.bId))]; const bRows = bIds.length ? await db.select({ id: competitionEntries.id, name: competitionEntries.name }).from(competitionEntries).where(inArray(competitionEntries.id, bIds)) : []; const bNames = new Map(bRows.map((row) => [row.id, row.name]));
  return { awards: rows.filter((row) => row.submittedByUserId === currentUserId || isPublicCommunityAward(row.status, row.reviewedAt)).map((row) => ({ id: row.id, submittedByUserId: row.submittedByUserId, name: row.name, condition: row.condition, prize: row.prize, supplementaryNote: row.supplementaryNote, publicNote: row.publicNote, reviewNote: row.submittedByUserId === currentUserId ? row.reviewNote : null, status: row.status, submitterName: getPublicDisplayName(row.submitter), recipientName: row.recipient ? getPublicDisplayName(row.recipient) : null, outcomeNote: row.outcomeNote })), candidates, matches: matchRows.map((row) => ({ id: row.id, label: presentMatchLabel({ stage: row.stage, stageName: stagePlan.find((stage) => stage.key === row.stage)?.name, round: row.round, entryRound: row.entryRound, teamAName: row.aName, teamBName: bNames.get(row.bId) ?? "TBD" }) })) };
}
export default async function CommunityAwardsPage({ params }: { params: Promise<{ seasonSlug: string }> }) { const { seasonSlug } = await params; const season = await db.query.seasons.findFirst({ where: eq(seasons.slug, seasonSlug) }); if (!season) notFound(); const authorization = await getCurrentUserAuthorization(); const data = await getPublicAwardData(season.id, authorization?.userId ?? null, normalizeStagePlan(season.stagePlan)); return <div className="container mx-auto max-w-3xl space-y-6 px-4 py-8"><div><h1 className="text-2xl font-bold">社区奖 · {season.name}</h1><p className="mt-1 text-sm text-[var(--color-fg-mid)]">社区提出创意，赛事方审核与确认结果；不替代正式赛事荣誉。</p></div><CommunityAwardsBoard seasonId={season.id} awards={data.awards} currentUserId={authorization?.userId ?? null} isAdmin={false} candidates={data.candidates} matches={data.matches} /></div>; }
